<?php

// $Id$

/**
 * @file
 * Install EZProzy module
 */
 
/**
 * Implementation of hook_install()
 *
 */
function ezproxy_install() {
  drupal_set_message(t('EZProxy module installed'));
}

/**
 * Implementation of hook_uninstall()
 *
 */
function ezproxy_uninstall() {
  variable_del("ezproxy_host");
  variable_del("ezproxy_password");
  variable_del("ezproxy_username");
  
  drupal_set_message(t('EZProxy module uninstalled'));
}
